<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9311dcfb-f12c-4c40-9c73-d039d90736b1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiLibrary.Infrastructure\AiLibrary.Infrastructure.csproj" />
    <ProjectReference Include="..\AiLibrary.Application\AiLibrary.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Middlewares\" />
    <Folder Include="Configuration\" />
  </ItemGroup>

</Project>
