// <auto-generated />
using System;
using AiLibrary.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiLibrary.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20260812070036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AiLibrary.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Blurb")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReadingLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Author = "J.R.R. Tolkien",
                            Blurb = "A reluctant hobbit joins dwarves on a treasure quest filled with wit and wonder.",
                            Genre = "Fantasy",
                            PageCount = 310,
                            ReadingLevel = "Middle grade / YA+",
                            Tags = "adventureclassicquestdragons",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Author = "Ursula K. Le Guin",
                            Blurb = "A gifted young mage must face the shadow unleashed by his own pride.",
                            Genre = "Fantasy",
                            PageCount = 183,
                            ReadingLevel = "YA / Adult",
                            Tags = "magiccoming-of-ageclassic",
                            Title = "A Wizard of Earthsea"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Author = "Jane Austen",
                            Blurb = "Sharp social comedy about first impressions, pride, and unlikely affection.",
                            Genre = "Romance / Classic",
                            PageCount = 432,
                            ReadingLevel = "Adult",
                            Tags = "romanceclassicwit",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Author = "Agatha Christie",
                            Blurb = "Hercule Poirot investigates a locked-train murder with too many suspects.",
                            Genre = "Mystery",
                            PageCount = 256,
                            ReadingLevel = "Adult",
                            Tags = "detectiveclassicpuzzle",
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Author = "Frank Herbert",
                            Blurb = "Political intrigue and destiny collide on a desert planet that holds the universe's most valuable resource.",
                            Genre = "Science Fiction",
                            PageCount = 688,
                            ReadingLevel = "Adult",
                            Tags = "epicpoliticsworldbuilding",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            Author = "F. Scott Fitzgerald",
                            Blurb = "Jazz Age tragedy of longing, wealth, and the American dream.",
                            Genre = "Literary Fiction",
                            PageCount = 180,
                            ReadingLevel = "Adult / YA+",
                            Tags = "classicshorttragedy",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            Author = "Octavia E. Butler",
                            Blurb = "A modern woman is pulled through time into the brutal realities of antebellum slavery.",
                            Genre = "Science Fiction / Historical",
                            PageCount = 287,
                            ReadingLevel = "Adult",
                            Tags = "time-travelpowerfulthoughtful",
                            Title = "Kindred"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            Author = "Madeline Miller",
                            Blurb = "A vivid reimagining of the witch of Aiaia finding power and voice among gods and mortals.",
                            Genre = "Mythic Fiction",
                            PageCount = 393,
                            ReadingLevel = "Adult",
                            Tags = "mythologyfeministlush-prose",
                            Title = "Circe"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            Author = "Andy Weir",
                            Blurb = "A lone astronaut wakes on a mission to save Earth — with science, humor, and unlikely friendship.",
                            Genre = "Science Fiction",
                            PageCount = 476,
                            ReadingLevel = "Adult",
                            Tags = "spaceproblem-solvingfun",
                            Title = "Project Hail Mary"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            Author = "L.M. Montgomery",
                            Blurb = "Imaginative orphan Anne Shirley transforms a quiet farm community with spirit and heart.",
                            Genre = "Classic / Coming of Age",
                            PageCount = 320,
                            ReadingLevel = "Middle grade / YA",
                            Tags = "cozyclassicfriendship",
                            Title = "Anne of Green Gables"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Author = "Erin Morgenstern",
                            Blurb = "A mysterious circus becomes the stage for a magical competition and a forbidden romance.",
                            Genre = "Fantasy",
                            PageCount = 387,
                            ReadingLevel = "Adult / YA+",
                            Tags = "atmosphericromancemagic",
                            Title = "The Night Circus"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Author = "Agatha Christie",
                            Blurb = "Ten strangers invited to an island are killed one by one in a masterclass of suspense.",
                            Genre = "Mystery",
                            PageCount = 272,
                            ReadingLevel = "Adult",
                            Tags = "thrillerclassicisolated",
                            Title = "And Then There Were None"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
